# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_control/manipulator_adc.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class manipulator_adc(genpy.Message):
  _md5sum = "1750cc3164fbe6e56c557c43a182eb58"
  _type = "robot_control/manipulator_adc"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 base_fd
uint16 ac1_fd
uint16 ac2_fd
uint16 ac3_fd
uint16 wrist_fd
uint16 claw_fd	"""
  __slots__ = ['base_fd','ac1_fd','ac2_fd','ac3_fd','wrist_fd','claw_fd']
  _slot_types = ['uint16','uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base_fd,ac1_fd,ac2_fd,ac3_fd,wrist_fd,claw_fd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(manipulator_adc, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.base_fd is None:
        self.base_fd = 0
      if self.ac1_fd is None:
        self.ac1_fd = 0
      if self.ac2_fd is None:
        self.ac2_fd = 0
      if self.ac3_fd is None:
        self.ac3_fd = 0
      if self.wrist_fd is None:
        self.wrist_fd = 0
      if self.claw_fd is None:
        self.claw_fd = 0
    else:
      self.base_fd = 0
      self.ac1_fd = 0
      self.ac2_fd = 0
      self.ac3_fd = 0
      self.wrist_fd = 0
      self.claw_fd = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6H().pack(_x.base_fd, _x.ac1_fd, _x.ac2_fd, _x.ac3_fd, _x.wrist_fd, _x.claw_fd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base_fd, _x.ac1_fd, _x.ac2_fd, _x.ac3_fd, _x.wrist_fd, _x.claw_fd,) = _get_struct_6H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6H().pack(_x.base_fd, _x.ac1_fd, _x.ac2_fd, _x.ac3_fd, _x.wrist_fd, _x.claw_fd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base_fd, _x.ac1_fd, _x.ac2_fd, _x.ac3_fd, _x.wrist_fd, _x.claw_fd,) = _get_struct_6H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6H = None
def _get_struct_6H():
    global _struct_6H
    if _struct_6H is None:
        _struct_6H = struct.Struct("<6H")
    return _struct_6H
